// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liovbpznmvgypacbczmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpb3ZicHpubXZneXBhY2Jjem1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTQ3MjYsImV4cCI6MjA2NDczMDcyNn0.bSBbGS2oGGk63XX3LsTKwYO8cbmn61tEsXLpp8o6ZoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);